Specify latest facebook-android-sdk version to fix build error
oddbit/flutter_facebook_app_events pull request #201
Opened 2022-01-19 09:58 UTC by Ayman-Barghout

This PR aims to resolve the error in issue https://github.com/oddbit/flutter_facebook_app_events/issues/200

The PR is also related to the discussion in PR https://github.com/oddbit/flutter_facebook_app_events/pull/189

Thanks a lot for the package and the great work you are doing!

2022-01-31 02:25 UTC, ferysyukur commented on android/build.gradle
> +    implementation 'com.facebook.android:facebook-android-sdk:12.3.0'
Hi @Ayman-Barghout. Thank you for your solution. Right now, we use `+` in version to ignore update minor version in the future. I think we can use this solution to sync dependency https://stackoverflow.com/questions/35101206/android-studio-re-download-dependencies-and-sync-project

2022-01-31 02:27 UTC, DennisAlund requested changes

2022-01-31 02:27 UTC, DennisAlund commented on android/build.gradle
> -    implementation 'com.facebook.android:facebook-android-sdk:12.+'
Please provide information on what version your project resolved to as `12.+` should resolve to the latest, which is `12.3` at the time of writing (https://github.com/facebook/facebook-android-sdk/releases)

Please run a clean build/install and provide information on what version your setup resolved.

2022-02-25 02:25 UTC, DennisAlund commented
Closed due to inactivity.

2022-02-25 02:25 UTC, closed without merging