bumped FBSDKCoreKit and FBAudienceNetwork versions
oddbit/flutter_facebook_app_events pull request #328
Opened 2023-12-13 01:21 UTC by mohamed-socrates

2024-02-08 14:42 UTC, ferysyukur requested changes

2024-02-08 14:42 UTC, ferysyukur commented on ios/facebook_app_events.podspec
> +  s.dependency 'FBSDKCoreKit', '~> 16.3.1'
We're just update major and minor version. So we just updated with ~16.3.

2024-02-08 14:42 UTC, ferysyukur commented on ios/facebook_app_events.podspec
> +  s.dependency 'FBAudienceNetwork', '~> 6.14.0'
Same like comment above. We're just using ~> 6.14.

2024-03-25 14:13 UTC, MaximilianFlechtner commented
+1

2024-04-04 05:47 UTC, closed without merging