- Updated ios SDK from 16.1 to 16.3.1
oddbit/flutter_facebook_app_events pull request #331
Opened 2024-01-02 13:05 UTC by rahul-dezerv

- Upgraded Facebook SDK for iOS from 16.1 to 16.3.1

2024-01-18 11:38 UTC, Saifallak commented
@DennisAlund can you merge this?

2024-01-18 11:39 UTC, Saifallak commented on ios/facebook_app_events.podspec
> +  s.dependency 'FBAudienceNetwork', '~> 6.14.0'
```suggestion
  s.dependency 'FBAudienceNetwork', '~> 6.14'
```

2024-01-18 11:39 UTC, Saifallak commented on ios/facebook_app_events.podspec
> +  s.dependency 'FBSDKCoreKit', '~> 16.3.1'
```suggestion
  s.dependency 'FBSDKCoreKit', '~> 16.3'
```

2024-03-08 15:40 UTC, ventskus-roman commented
@volkankahraman until it's merged, you can use my fork (or create your own)

  facebook_app_events:
    git:
      url: https://github.com/ventskus-roman/flutter_facebook_app_events.git
      ref: ef8b7266b8ab7772159e4703a2d7d1d3addbbbc7

2024-03-19 23:05 UTC, volkankahraman commented
@ventskus-roman  Thanks!

2024-03-25 14:13 UTC, MaximilianFlechtner commented
+1

2024-03-27 13:25 UTC, Saifallak requested changes

2024-03-27 13:25 UTC, Saifallak commented on ios/facebook_app_events.podspec
> +  s.dependency 'FBAudienceNetwork', '~> 6.14'
```suggestion
  s.dependency 'FBAudienceNetwork', '~> 6.15'
```

According to [Meta Docs](https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/ios/add-sdk/)
they released on March 15, 2024 v-6.15

2024-03-27 17:50 UTC, antonoddbit commented
I still fixing another branch similar to this, and with less conflict.

2024-04-04 05:47 UTC, closed without merging